services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_permisos
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  ms-permisos:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      PORT: 8000
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ms_permisos
      REDIS_HOST: redis
      REDIS_PORT: 6379
      USERS_BASE_URL: http://ms-usuarios:8001
    command: sh -c "npm run migration:run && npm run seed && node dist/main.js"
    ports:
      - '8000:8000'
